INSERT INTO ACADEMIAS(DIRECTORNAME,TURNOPROFESOR,PROFESORES_PROFESORID)VALUES('Rodrigo Castro','Mañana',1);
INSERT INTO ACADEMIAS(DIRECTORNAME,TURNOPROFESOR,PROFESORES_PROFESORID)VALUES('MARIANA PLAZA','TARDE',2);

INSERT INTO PROFESORES(TIPOCONTRATO,NOMBREPROFESOR,ESPECIALIDADPROFESOR)VALUES('PLANTA','RODRIGO CASTRO','MUSICA');
INSERT INTO PROFESORES(TIPOCONTRATO,NOMBREPROFESOR,ESPECIALIDADPROFESOR)VALUES('HONORARIOS','MARIANA PLAZA','DANZA');

INSERT INTO MUNICIPALIDADES(NOMBREMUNI,REGION,ACADEMIAS_ACADEMIAID)VALUES('SANTIAGO','METRO',4);
INSERT INTO MUNICIPALIDADES(NOMBREMUNI,REGION,ACADEMIAS_ACADEMIAID)VALUES('VALPARAISO','V',5);

INSERT INTO CURSOS(NOMBRECURSO, NUMEROSALA, CAPACIDADSALA,ACADEMIAS_ACADEMIAID)VALUES('GUITARRA CUECA',21,40,4);
INSERT INTO CURSOS(NOMBRECURSO, NUMEROSALA, CAPACIDADSALA,ACADEMIAS_ACADEMIAID)VALUES('DANZA CHILOTA',22,30,5);



